from pathlib import Path

app = Path('src/App.jsx')
s = app.read_text()

s = s.replace('  Loader2, Plus, Trash2, Save, Sparkles, Phone, ArrowLeft\n', '  Loader2, Plus, Trash2, Save, Sparkles, Phone, ArrowLeft, Bell, Megaphone, UserX, CheckCircle2\n')
s = s.replace('const FONT_IMPORT = `', 'const VAPID_PUBLIC_KEY = "BEru2qidulN7jy7Bg_eAVD6v1R__kAnOuZV69RoSV_7kzWF2-6S88sKB2JLC-dBLWvcdlOhA6dPKtZnFVYIxNj4";\n\nconst FONT_IMPORT = `', 1)

old = '''    const [usersR, teachersR, parentsR, studentsR, regsR] = await Promise.all([\n      supabase.from("users").select("*"),\n      supabase.from("teachers").select("*"),\n      supabase.from("parents").select("*"),\n      supabase.from("students").select("*"),\n      supabase.from("registrations").select("*").order("created_at", { ascending: false }),\n    ]);\n    return {\n      users: usersR.data || [],\n      teachers: teachersR.data || [],\n      parents: parentsR.data || [],\n      students: (studentsR.data || []).map(studentFromRow),\n      registrations: (regsR.data || []).map(regFromRow),\n    };'''
new = '''    const [usersR, teachersR, parentsR, studentsR, regsR, announcementsR, attendanceR] = await Promise.all([\n      supabase.from("users").select("*"),\n      supabase.from("teachers").select("*"),\n      supabase.from("parents").select("*"),\n      supabase.from("students").select("*"),\n      supabase.from("registrations").select("*").order("created_at", { ascending: false }),\n      supabase.from("announcements").select("*").order("created_at", { ascending: false }).limit(20),\n      supabase.from("attendance").select("*").order("date", { ascending: false }).limit(1000),\n    ]);\n    return {\n      users: usersR.data || [],\n      teachers: teachersR.data || [],\n      parents: parentsR.data || [],\n      students: (studentsR.data || []).map(studentFromRow),\n      registrations: (regsR.data || []).map(regFromRow),\n      announcements: announcementsR.data || [],\n      attendance: attendanceR.data || [],\n    };'''
if old not in s: raise SystemExit('fetchAll pattern not found')
s = s.replace(old, new, 1)
s = s.replace('setData({ users: [], teachers: [], parents: [], students: [], registrations: [] });', 'setData({ users: [], teachers: [], parents: [], students: [], registrations: [], announcements: [], attendance: [] });')
s = s.replace('["students", "teachers", "parents", "registrations", "users"].forEach', '["students", "teachers", "parents", "registrations", "users", "announcements", "attendance"].forEach')

needle = '''    deleteParent: (id) => mutate(async () => {\n      const { error } = await supabase.from("users").delete().eq("id", id);\n      if (error) throw error;\n    }),\n    clearDemoData:'''
insert = '''    deleteParent: (id) => mutate(async () => {\n      const { error } = await supabase.from("users").delete().eq("id", id);\n      if (error) throw error;\n    }),\n    deleteStudent: (id) => mutate(async () => {\n      const { error } = await supabase.from("students").delete().eq("id", id);\n      if (error) throw error;\n    }),\n    markAttendance: (studentId, status, date, teacherId) => mutate(async () => {\n      const { error } = await supabase.from("attendance").upsert({ student_id: studentId, date, status, teacher_id: teacherId, updated_at: new Date().toISOString() }, { onConflict: "student_id,date" });\n      if (error) throw error;\n      try { await supabase.functions.invoke("send-push", { body: { type: "attendance", sender_user_id: teacherId, student_id: studentId, status, date } }); } catch (e) { console.warn("Push notification failed", e); }\n    }),\n    addAnnouncement: (form, adminId) => mutate(async () => {\n      const { data: row, error } = await supabase.from("announcements").insert({ title: form.title, body: form.body, created_by: adminId, target_role: form.targetRole || "all" }).select().single();\n      if (error) throw error;\n      try { await supabase.functions.invoke("send-push", { body: { type: "announcement", sender_user_id: adminId, announcement_id: row.id } }); } catch (e) { console.warn("Push notification failed", e); }\n    }),\n    deleteAnnouncement: (id) => mutate(async () => {\n      const { error } = await supabase.from("announcements").delete().eq("id", id);\n      if (error) throw error;\n    }),\n    clearDemoData:'''
if needle not in s: raise SystemExit('api pattern not found')
s = s.replace(needle, insert, 1)

needle = 'function DashboardShell({ title, subtitle, icon: Icon, user, onLogout, children, data, api }) {'
helper = '''function urlBase64ToUint8Array(base64String) {\n  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);\n  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");\n  return Uint8Array.from(window.atob(base64), (c) => c.charCodeAt(0));\n}\n\nfunction PushNotifications({ user }) {\n  const [state, setState] = useState("idle");\n  const supported = typeof window !== "undefined" && "serviceWorker" in navigator && "PushManager" in window && "Notification" in window;\n  const enable = async () => {\n    if (!supported) { setState("unsupported"); return; }\n    try {\n      setState("loading");\n      const permission = await Notification.requestPermission();\n      if (permission !== "granted") { setState("denied"); return; }\n      const registration = await navigator.serviceWorker.ready;\n      let subscription = await registration.pushManager.getSubscription();\n      if (!subscription) subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY) });\n      const json = subscription.toJSON();\n      const { error } = await supabase.from("push_subscriptions").upsert({ user_id: user.id, endpoint: json.endpoint, p256dh: json.keys?.p256dh || "", auth: json.keys?.auth || "", user_agent: navigator.userAgent, updated_at: new Date().toISOString() }, { onConflict: "user_id,endpoint" });\n      if (error) throw error;\n      setState("enabled");\n    } catch (e) { console.error(e); setState("error"); }\n  };\n  return <button className="btn btn-ghost" onClick={enable} disabled={state === "loading" || state === "enabled"}><Bell size={15} /> {state === "enabled" ? "الإشعارات مفعّلة" : state === "loading" ? "جارٍ التفعيل..." : "تفعيل الإشعارات"}</button>;\n}\n\nfunction AnnouncementFeed({ announcements, role }) {\n  const visible = (announcements || []).filter(a => a.target_role === "all" || a.target_role === role);\n  if (!visible.length) return null;\n  return <section className="announcement-feed"><div className="section-head"><div><div className="section-kicker"><Megaphone size={15} /> إعلانات المعهد</div><h3>آخر الإعلانات</h3></div></div><div className="announcement-list">{visible.map(a => <article className="announcement-card" key={a.id}><div className="announcement-icon"><Megaphone size={18} /></div><div><h4>{a.title}</h4><p>{a.body}</p><small>{new Date(a.created_at).toLocaleDateString("ar-EG")}</small></div></article>)}</div></section>;\n}\n\n''' + needle
if needle not in s: raise SystemExit('shell pattern not found')
s = s.replace(needle, helper, 1)
s = s.replace('<span className="dash-user">{user.name}</span>\n          {data && api && (', '<span className="dash-user">{user.name}</span>\n          <PushNotifications user={user} />\n          {data && api && (', 1)
s = s.replace('<main className="dash-body">{children}</main>', '<main className="dash-body"><AnnouncementFeed announcements={data?.announcements} role={user.role} />{children}</main>', 1)

s = s.replace('[["overview", "طلبات التسجيل"], ["students", "الطلاب"], ["teachers", "المعلمون"], ["accounts", "الحسابات"]]', '[["overview", "طلبات التسجيل"], ["students", "الطلاب"], ["teachers", "المعلمون"], ["announcements", "الإعلانات"], ["accounts", "الحسابات"]]', 1)

needle = '  const pending = data.registrations.filter((r) => r.status === "pending");'
insert = '''  const [announcementForm, setAnnouncementForm] = useState({ title: "", body: "", targetRole: "all" });\n  const [announcementError, setAnnouncementError] = useState("");\n  const publishAnnouncement = async (e) => {\n    e.preventDefault(); setAnnouncementError("");\n    if (!announcementForm.title.trim() || !announcementForm.body.trim()) { setAnnouncementError("اكتب عنوان الإعلان ونصه."); return; }\n    setBusyId("announcement"); const result = await api.addAnnouncement(announcementForm, user.id); setBusyId(null);\n    if (!result.ok) { setAnnouncementError("تعذر نشر الإعلان. تأكد من إعداد قاعدة البيانات."); return; }\n    setAnnouncementForm({ title: "", body: "", targetRole: "all" });\n  };\n  const deleteAnnouncement = async (id) => { if (!window.confirm("هل تريد حذف هذا الإعلان؟")) return; await api.deleteAnnouncement(id); };\n\n''' + needle
if needle not in s: raise SystemExit('pending pattern not found')
s = s.replace(needle, insert, 1)

needle = '              <div style={{ width: 140 }}><BehaviorBar value={s.behavior} /></div>\n            </div>'
replace = '''              <div style={{ display: "flex", alignItems: "center", gap: 10 }}><div style={{ width: 140 }}><BehaviorBar value={s.behavior} /></div><button className="btn btn-outline btn-sm" onClick={async () => { if (window.confirm(`سيتم حذف الطالب ${s.name} نهائيًا. هل أنت متأكد؟`)) await api.deleteStudent(s.id); }}><UserX size={14} /> إزالة</button></div>\n            </div>'''
if needle not in s: raise SystemExit('student row pattern not found')
s = s.replace(needle, replace, 1)

needle = '      {tab === "accounts" && ('
ann = '''      {tab === "announcements" && (\n        <div><form className="inline-form announcement-admin-form" onSubmit={publishAnnouncement}><div className="form-grid"><div className="field-row"><label className="field-label">عنوان الإعلان</label><input className="input" value={announcementForm.title} onChange={e => setAnnouncementForm({ ...announcementForm, title: e.target.value })} placeholder="مثال: دوام المعهد غدًا" /></div><div className="field-row"><label className="field-label">الفئة المستهدفة</label><select className="input" value={announcementForm.targetRole} onChange={e => setAnnouncementForm({ ...announcementForm, targetRole: e.target.value })}><option value="all">الجميع</option><option value="parent">أولياء الأمور</option><option value="teacher">المعلمون</option></select></div></div><div className="field-row"><label className="field-label">نص الإعلان</label><textarea className="input" rows={5} value={announcementForm.body} onChange={e => setAnnouncementForm({ ...announcementForm, body: e.target.value })} placeholder="اكتب الإعلان هنا..." /></div>{announcementError && <div className="error-note"><X size={14} /> {announcementError}</div>}<button className="btn btn-primary" disabled={busyId === "announcement"}>{busyId === "announcement" ? <Loader2 size={15} className="spin" /> : <Megaphone size={15} />} نشر الإعلان وإرسال إشعار</button></form><div className="list">{(data.announcements || []).map(a => <div className="list-row" key={a.id}><div><div className="list-row-title">{a.title}</div><div className="list-row-sub">{a.body}</div></div><button className="btn btn-outline btn-sm" onClick={() => deleteAnnouncement(a.id)}><Trash2 size={14} /> حذف</button></div>)}{!(data.announcements || []).length && <div className="empty-note">لا توجد إعلانات منشورة.</div>}</div></div>\n      )}\n\n''' + needle
if needle not in s: raise SystemExit('accounts pattern not found')
s = s.replace(needle, ann, 1)

needle = 'function TeacherDashboard({ data, api, user, onLogout }) {'
attendance = '''function AttendancePanel({ student, records, teacherId, api }) {\n  const today = new Date().toISOString().slice(0, 10);\n  const current = records.find(r => r.student_id === student.id && r.date === today);\n  const [busy, setBusy] = useState(false);\n  const mark = async (status) => { setBusy(true); await api.markAttendance(student.id, status, today, teacherId); setBusy(false); };\n  return <div className="attendance-panel"><div><div className="section-kicker"><ClipboardCheck size={15} /> حضور اليوم</div><strong>{current?.status === "present" ? "حاضر اليوم" : current?.status === "absent" ? "غائب اليوم" : "لم يُسجل الحضور بعد"}</strong></div><div className="attendance-actions"><button className="btn btn-primary attendance-present" onClick={() => mark("present")} disabled={busy || current?.status === "present"}><CheckCircle2 size={16} /> حاضر</button><button className="btn btn-outline attendance-absent" onClick={() => mark("absent")} disabled={busy || current?.status === "absent"}><X size={16} /> غائب</button></div></div>;\n}\n\n''' + attendance + needle
if needle not in s: raise SystemExit('teacher pattern not found')
s = s.replace(needle, attendance, 1)
needle = '''          {selected ? (\n            <StudentCard key={selected.id} student={selected} teacherName={user.name} editable onSave={save} saving={saving} />\n          ) :'''
replace = '''          {selected ? (\n            <>\n              <AttendancePanel student={selected} records={data.attendance || []} teacherId={user.id} api={api} />\n              <StudentCard key={selected.id} student={selected} teacherName={user.name} editable onSave={save} saving={saving} />\n            </>\n          ) :'''
if needle not in s: raise SystemExit('selected pattern not found')
s = s.replace(needle, replace, 1)

needle = '            return <StudentCard key={s.id} student={s} teacherName={teacher?.name} editable={false} />;'
replace = '            const today = new Date().toISOString().slice(0, 10); const attendance = (data.attendance || []).find(r => r.student_id === s.id && r.date === today); return <div key={s.id}><div className="parent-attendance-badge">{attendance?.status === "present" ? "✓ حاضر اليوم" : attendance?.status === "absent" ? "✕ غائب اليوم" : "لم يسجل الحضور بعد"}</div><StudentCard student={s} teacherName={teacher?.name} editable={false} /></div>;'
if needle not in s: raise SystemExit('parent pattern not found')
s = s.replace(needle, replace, 1)

css = '''        .attendance-panel { background: var(--surface); border: 1px solid var(--border); border-radius: 16px; padding: 14px 16px; margin-bottom: 16px; display: flex; align-items: center; justify-content: space-between; gap: 14px; flex-wrap: wrap; }\n        .attendance-actions { display: flex; gap: 8px; flex-wrap: wrap; }\n        .attendance-present, .attendance-absent { min-width: 110px; }\n        .section-kicker { display: flex; align-items: center; gap: 6px; color: var(--green-700); font-size: 12px; font-weight: 800; margin-bottom: 3px; }\n        .announcement-feed { margin-bottom: 20px; } .announcement-feed h3 { color: var(--green-900); font-size: 18px; }\n        .announcement-list { display: grid; gap: 10px; margin-top: 10px; }\n        .announcement-card { display: flex; gap: 12px; align-items: flex-start; background: var(--surface); border: 1px solid var(--border); border-right: 4px solid var(--gold-500); border-radius: 14px; padding: 14px; }\n        .announcement-icon { width: 38px; height: 38px; flex: 0 0 38px; border-radius: 11px; background: #F7F1DD; color: var(--gold-500); display: flex; align-items: center; justify-content: center; }\n        .announcement-card h4 { margin: 0 0 4px; color: var(--green-900); font-size: 14px; } .announcement-card p { color: var(--ink); font-size: 13px; line-height: 1.75; white-space: pre-wrap; } .announcement-card small { display: block; margin-top: 5px; color: var(--muted); font-size: 10.5px; }\n        .parent-attendance-badge { display: inline-flex; margin: 0 0 7px; padding: 6px 10px; border-radius: 999px; background: #EEF7F1; color: var(--green-700); font-size: 11.5px; font-weight: 800; }\n        .announcement-admin-form { margin-bottom: 16px; }\n        @media (max-width: 760px) { .attendance-panel { align-items: stretch; } .attendance-actions { width: 100%; } .attendance-actions .btn { flex: 1; } }\n'''
idx = s.rfind('</style>')
if idx < 0: raise SystemExit('style close not found')
s = s[:idx] + css + s[idx:]

app.write_text(s)

sw = Path('public/sw.js') if Path('public/sw.js').exists() else Path('sw.js')
if sw.exists():
    w = sw.read_text()
    if 'self.addEventListener("push"' not in w:
        w += '''\n\nself.addEventListener("push", (event) => {\n  let data = {};\n  try { data = event.data ? event.data.json() : {}; } catch { data = { body: event.data?.text() || "" }; }\n  event.waitUntil(self.registration.showNotification(data.title || "معهد البر", { body: data.body || "لديك إشعار جديد من معهد البر.", icon: "/icons/icon-192.png", badge: "/icons/icon-192.png", dir: "rtl", lang: "ar", data: { url: data.url || "/" } }));\n});\n\nself.addEventListener("notificationclick", (event) => {\n  event.notification.close();\n  const url = event.notification.data?.url || "/";\n  event.waitUntil(clients.matchAll({ type: "window", includeUncontrolled: true }).then((list) => { const existing = list.find((client) => "focus" in client); if (existing) { existing.navigate(url); return existing.focus(); } return clients.openWindow(url); }));\n});\n'''
        sw.write_text(w)
else:
    raise SystemExit('service worker not found')
